// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDveI0AHNA2KWc4jhEAtVd45YT05cyRBOc',
    appId: '1:386927622635:web:0f1981fe535085f81401ae',
    messagingSenderId: '386927622635',
    projectId: 'noticeboardapp-c42f2',
    authDomain: 'noticeboardapp-c42f2.firebaseapp.com',
    storageBucket: 'noticeboardapp-c42f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgAzLKR6zwErMERp3XOMfZ45tNHrrGRds',
    appId: '1:386927622635:android:467809cd780184ea1401ae',
    messagingSenderId: '386927622635',
    projectId: 'noticeboardapp-c42f2',
    storageBucket: 'noticeboardapp-c42f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUU4vjWD7zReQwaAcyynd2lNzPLwvXpqk',
    appId: '1:386927622635:ios:e3716406995e0f711401ae',
    messagingSenderId: '386927622635',
    projectId: 'noticeboardapp-c42f2',
    storageBucket: 'noticeboardapp-c42f2.appspot.com',
    iosBundleId: 'com.example.flutterNoticeBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUU4vjWD7zReQwaAcyynd2lNzPLwvXpqk',
    appId: '1:386927622635:ios:a3fab18235e489701401ae',
    messagingSenderId: '386927622635',
    projectId: 'noticeboardapp-c42f2',
    storageBucket: 'noticeboardapp-c42f2.appspot.com',
    iosBundleId: 'com.example.flutterNoticeBoardApp.RunnerTests',
  );
}
